### ISSUE TITLE
VS 2010 won't open AtomLauncher.sln

### ISSUE THREAD

**Issue by lucas993** [Xcodo/atom-launcher#1]
I'm not sure if it should?   Perhaps there's a binary download somewhere?

**Comment by Xcodo** [comment]
The project was made in VS 2015 Community Edition.

[This SO answer](http://stackoverflow.com/a/31600348) suggests that it may be supposed to work with service pack 1 of VS 2010, but I don't know if I've included any VS 2012/2013/2015 features which would preclude that.

Anyway, the binary is available as a GitHub release [here](https://github.com/Xcodo/atom-launcher/releases).

Let me know how you get on.

**Comment by Xcodo** [comment]
I also added installation instructions to the README.

**Comment by lucas993** [comment]
:+1:
